version: '3'

services:
  simulation:
    image: mysteriouscrawler/test
    ports:
      - "3000:3000"

  rtc-app:
    build:
      context: .
      dockerfile: src/docker/Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - simulation
    environment:
      MYSTERIOUS_CRAWLER_API_URL: "http://simulation:3000/api"